let answers = [
  { type: 'radio', search: 'заснована всесвітня організація', answer: 'липня' },
  { type: 'radio', search: 'права належать до всесвітньої', answer: 'фонограми й програми' },
  { type: 'radio', search: 'об\'єктами авторського', answer: 'твори науки' },
  { type: 'radio', search: 'основних принципів авторського', answer: 'невідчужуваність особистих немайнових' },
  { type: 'radio', search: 'принципів патентного права', answer: 'патенту виняткового права' },
  { type: 'radio', search: 'cпецифічні об\'єкти інтелектуальної', answer: '50' },
  { type: 'radio', search: 'специфічних об\'єктів інтелектуальної', answer: 'програми і компіляції' },
  { type: 'radio', search: 'надається правова охорона', answer: 'мікроорганізму' },
  { type: 'radio', search: 'поняття інтелектуальної власності', answer: 'суміжне' },
  { type: 'radio', search: 'без права власності', answer: 'ні' },
  { type: 'radio', search: 'про власність', answer: 'лютого' },
  { type: 'radio', search: 'році набрала чинності', answer: '1970' },
  { type: 'radio', search: 'що таке винахід', answer: 'сфері технології' },
  { type: 'radio', search: 'що таке пристрій', answer: 'штучно створена' },
  { type: 'radio', search: 'що таке штам', answer: 'однорідні культури' },
  { type: 'radio', search: 'що таке спосіб', answer: 'дій над матеріальним' },
  { type: 'radio', search: 'промисловий знак', answer: 'конструктивне вирішення' },
  { type: 'radio', search: 'видачу патенту', answer: 'реферат' },
  { type: 'radio', search: 'скільки часу', answer: '12' },
  { type: 'radio', search: 'патентний фонд', answer: 'матеріалів з питань' },
  { type: 'radio', search: 'патентна інформація', answer: 'відомств різних країн' },
  { type: 'radio', search: 'патентний бюлетень', answer: 'угод з питань' },
  { type: 'radio', search: 'міжнародна патентна класифікація', answer: 'відомств багатьох держав' },
  { type: 'radio', search: 'призначення міжнародна', answer: 'для уніфікованого' },
  { type: 'radio', search: 'зображальних елементів', answer: '1973' },
  { type: 'radio', search: 'чинності віденська', answer: 'серпня' },
  { type: 'radio', search: 'введена міжнародна', answer: '8 жовтня 1968' },
  { type: 'radio', search: 'інтелектуальна економіка', answer: 'галузь знань' },
  { type: 'radio', search: 'ринкова інтелектуальна', answer: 'змішана економіка' },
  { type: 'radio', search: 'бізнес - це', answer: 'комерціалізації' },
  { type: 'radio', search: 'формою власності', answer: 'приватним' },
  { type: 'radio', search: 'службові', answer: 'трудовому договорі' },
  { type: 'radio', search: 'службове', answer: 'роботодавця' },
  { type: 'radio', search: 'трудовий договір', answer: 'плату і забезпечувати' },
  { type: 'radio', search: 'програмний продукт', answer: 'тестувати' },
  { type: 'radio', search: 'таке програмне забезпечення', answer: 'всі програми' },
  { type: 'radio', search: 'таке продукт', answer: 'єдиному' },
  { type: 'radio', search: 'таке проектне завдання', answer: 'рамках' },
  { type: 'radio', search: 'таке проектне рішення', answer: 'достатнє' },
  { type: 'radio', search: 'проектний документ', answer: 'програмістам' },
  { type: 'radio', search: 'таке проектування', answer: 'неіснуючого' },
  { type: 'radio', search: 'Специфічні об\'єкти інтелектуальної власності', answer: '50' },

  { type: 'checkbox', search: 'винаходу може', answer: ['штам', 'спосіб', 'раніше'] },
  { type: 'checkbox', search: 'ринкового товару', answer: ['корисність', 'рідкість', 'універсальність'] },
  { type: 'checkbox', search: 'підходами', answer: ['дохідний', 'витратний', 'порівняльний'] },
  { type: 'checkbox', search: 'авторському', answer: ['сторони', 'територія', 'порядок'] },
  { type: 'checkbox', search: 'вирішити', answer: ['раптовому', 'ускладнень', 'попиту'] },
  { type: 'checkbox', search: 'придбання', answer: ['освоїти', 'знизити', 'зовнішньому'] },
  { type: 'checkbox', search: 'видами порушення', answer: ['плагіат', 'пірацтво', 'контрафакція'] },
  { type: 'checkbox', search: 'завданням ставить', answer: ['покращення', 'заохочення', 'модернізацію'] },
  { type: 'checkbox', search: 'дієві', answer: ['вихідний код', 'алгоритми', 'назву'] },
  { type: 'checkbox', search: 'комерційної', answer: ['50', 'від 2 до'] },
  { type: 'checkbox', search: 'характерні', answer: ['художня', 'технічна'] },
  { type: 'checkbox', search: 'нормативними', answer: ['цивільним', 'авторське'] },
  { type: 'checkbox', search: 'наведеного', answer: ['генеральна', 'конференція', 'комітет'] },
  { type: 'checkbox', search: 'немайнове', answer: ['авторство', 'недоторканість'] },

  { type: 'select', answer: 'особи на результат', search: 'Інтелектуальна власність' },
  { type: 'select', answer: 'гуманітарній сфері', search: 'Результат художньої творчості' },
  { type: 'select', answer: 'представлених на ринку', search: 'Об\'єкти промислової власності' },
  { type: 'select', answer: 'меншою мірою', search: 'Об\'єкти авторського права і суміжних прав' },
  { type: 'select', answer: 'не стільки створені', search: 'Комерційні позначення' },
  { type: 'select', answer: 'в будь-якій сфері', search: 'винахід' },
  { type: 'select', answer: 'у сфері продукції', search: 'Корисна модель' },
  { type: 'select', answer: 'невідомих раніше', search: 'Наукове відкриття' },
  { type: 'select', answer: 'секретною', search: 'Комерційна пропозиція' },
  { type: 'select', answer: 'комбінація', search: 'Торгова марка' },
  { type: 'select', answer: 'прикладне значення', search: 'Результат технічної' },
  { type: 'select', answer: 'їхнього створення', search: 'Державна система інтелектуальної власності' },
  { type: 'select', answer: 'експертних', search: 'Установа' },
  { type: 'select', answer: 'експертних', search: 'Державна система правової охорони інтелектуальної власності' },
  { type: 'select', answer: 'урядовий орган', search: 'Державна служба інтелектуальної власності' },
  { type: 'select', answer: 'охорона надається автоматично', search: 'Принцип автоматичної охорони літературних та художніх творів' },
  { type: 'select', answer: 'одержувати у всіх інших', search: 'Принцип національного режиму охорони літературних та художніх творів' },
  { type: 'select', answer: 'походження твору', search: 'Принцип незалежності охорони' },
  { type: 'select', answer: 'промисловий зразок', search: 'Патент' },
  { type: 'select', answer: 'суміжних прав, комерційні позначення', search: 'Свідоцтво' },
  { type: 'select', answer: 'взаємовигідних', search: 'Комерціалізація об\'єктів інтелектуальної власності' },
  { type: 'select', answer: 'обумовлена', search: 'Виключна ліцензія' },
  { type: 'select', answer: 'ліцензіаром цього', search: 'Одинична ліцензія' },
  { type: 'select', answer: 'видачі ним іншим особам', search: 'Невиключна ліцензія' },
  { type: 'select', answer: 'розрахункова сума', search: 'Ринкова вартість' },
  { type: 'select', answer: 'доопрацювання', search: 'Вартість утилізації' },
  { type: 'select', answer: 'конкретних методик', search: 'Вартість для страхування та оподаткування' },
  { type: 'select', answer: 'представить', search: 'Інвестиційна власність' }
]